### ISSUE TITLE
Error StackOverflow

### ISSUE THREAD

**Issue by gabicavalcante** [ace-design/island#63]
When I try to run the code with high values of resource(s) (ex: 7000 WOOD), this error happens (as the picture show). I'm using the map of the week 05, with this informations in the main class:

```
class Main {
    public static void main(String[] args) throws Exception {
        run(Explorer.class)
                .exploring(new File("src/main/resource/week05/_map.json"))
                .withSeed(0L)
                .startingAt(1, 1, "SOUTH")
                .backBefore(20000)
                .withCrew(15)
                .collecting(7000,  "WOOD")
                .storingInto("src/main/resource/output")
                .fire();
    }
}
```

<img width="775" alt="captura de tela 2016-03-06 as 15 44 56" src="https://cloud.githubusercontent.com/assets/5027428/13556865/1f1f0580-e3e4-11e5-9bc8-432ba13d8a21.png">

**Comment by mosser** [comment]
As the play method is now tail recursive, this is quite annoying. In order to reproduce it, I have to mock a bot that will never stop, but still replying valid decisions. Work in progress.

Ps. you're not loading the resource as it should be. Use the Resource API instead of creating a file, especially if you put your maps in the resources directory.

**Comment by gabicavalcante** [comment]
Thank you, I will change to use the Resource API instead.
